version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - backend

  gateway-service:
    build: ./backend/gateway-service
    hostname: gateway-service
    ports:
      - 3000:3000
    volumes:
      - ./backend/gateway-service:/var/www/gateway-service
      - /var/www/gateway-service/node_modules
    # depends_on:
    #   - rabbitmq
    # environment:
    #   WAIT_HOSTS: rabbitmq:5672
    #   WAIT_TIMEOUT: 120
    #   WAIT_SLEEP_INTERVAL: 5
    networks:
      - backend
      - frontend

  dropbox-service:
    build: ./backend/dropbox-service
    hostname: dropbox-service
    volumes:
      - ./backend/dropbox-service:/var/www/dropbox-service
      - /var/www/dropbox-service/node_modules
    # depends_on:
    #   - rabbitmq
    # environment:
    #   WAIT_HOSTS: rabbitmq:5672
    #   WAIT_TIMEOUT: 120
    #   WAIT_SLEEP_INTERVAL: 5
    networks:
      - backend

  logger-service:
    build: ./backend/logger-service
    hostname: logger-service
    volumes:
      - ./backend/logger-service:/var/www/logger-service
      - /var/www/logger-service/node_modules
    depends_on:
      - rabbitmq
    environment:
      WAIT_HOSTS: rabbitmq:5672
      WAIT_TIMEOUT: 120
      WAIT_SLEEP_INTERVAL: 5
    networks:
      - backend

  minio-service:
    build: ./backend/minio-service
    hostname: minio-service
    volumes:
      - ./backend/minio-service:/var/www/minio-service
      - /var/www/minio-service/node_modules
    # depends_on:
    #   - rabbitmq
    # environment:
    #   WAIT_HOSTS: rabbitmq:5672
    #   WAIT_TIMEOUT: 120
    #   WAIT_SLEEP_INTERVAL: 5
    networks:
      - backend

  mongodb-service:
    build: ./backend/mongodb-service
    hostname: mongodb-service
    volumes:
      - ./backend/mongodb-service:/var/www/mongodb-service
      - /var/www/mongodb-service/node_modules
    # depends_on:
    #   - rabbitmq
    # environment:
    #   WAIT_HOSTS: rabbitmq:5672
    #   WAIT_TIMEOUT: 120
    #   WAIT_SLEEP_INTERVAL: 5
    networks:
      - backend

  picture-service:
    build: ./backend/picture-service
    hostname: picture-service
    volumes:
      - ./backend/picture-service:/var/www/picture-service
      - /var/www/picture-service/node_modules
    # depends_on:
    #   - rabbitmq
    # environment:
    #   WAIT_HOSTS: rabbitmq:5672
    #   WAIT_TIMEOUT: 120
    #   WAIT_SLEEP_INTERVAL: 5
    networks:
      - backend
  
  # webclient:
  #   build: ./frontend
  #   volumes:
  #       - ./frontend:/var/www/frontend
  #       - /var/www/frontend/node_modules
  #   ports:
  #       - 4200:4200
  #   networks:
  #     - frontend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge