version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    env_file:
     - ./.develop.env
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - backend

  mongodb:
    image: mongo:5.0.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=nestjs
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - mongodb_internal

  gateway-service:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
      args:
        - BUILD_CONTEXT=gateway-service
    hostname: gateway-service
    volumes: 
      - ./backend/gateway-service:/base/backend/gateway-service/
      - ./backend/proto:/base/backend/proto/
      - ./backend/service-types/:/base/backend/service-types/
      - /base/node_modules
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
    environment:
      WAIT_HOSTS: rabbitmq:5672
    env_file:
      - ./.develop.env
    networks:
      - backend
      - frontend

  dropbox-service:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
      args:
        - BUILD_CONTEXT=dropbox-service
    hostname: dropbox-service
    volumes: 
      - ./backend/dropbox-service:/base/backend/dropbox-service/
      - ./backend/proto:/base/backend/proto/
      - ./backend/service-types/:/base/backend/service-types/
      - /base/node_modules
    # depends_on:
    #   - rabbitmq
    # environment:
    #   WAIT_HOSTS: rabbitmq:5672
    #   WAIT_TIMEOUT: 120
    #   WAIT_SLEEP_INTERVAL: 5
    env_file:
      - ./.develop.env
    networks:
      - backend

  logger-service:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
      args:
        - BUILD_CONTEXT=logger-service
    hostname: logger-service
    volumes: 
      - ./backend/logger-service:/base/backend/logger-service/
      - ./backend/proto:/base/backend/proto/
      - ./backend/service-types/:/base/backend/service-types/
      - /base/node_modules
    depends_on:
      - rabbitmq
    environment:
      WAIT_HOSTS: rabbitmq:5672
    env_file:
      - ./.develop.env
    networks:
      - backend

  minio-service:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
      args:
        - BUILD_CONTEXT=minio-service
    hostname: minio-service
    volumes: 
      - ./backend/minio-service:/base/backend/minio-service/
      - ./backend/proto:/base/backend/proto/
      - ./backend/service-types/:/base/backend/service-types/
      - /base/node_modules
    # depends_on:
    #   - rabbitmq
    # environment:
    #   WAIT_HOSTS: rabbitmq:5672
    #   WAIT_TIMEOUT: 120
    #   WAIT_SLEEP_INTERVAL: 5
    env_file:
      - ./.develop.env
    networks:
      - backend

  mongodb-service:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
      args:
        - BUILD_CONTEXT=mongodb-service
    hostname: mongodb-service
    volumes: 
      - ./backend/mongodb-service:/base/backend/mongodb-service/
      - ./backend/proto:/base/backend/proto/
      - ./backend/service-types/:/base/backend/service-types/
      - /base/node_modules
    depends_on:
      - rabbitmq
    environment:
      WAIT_HOSTS: rabbitmq:5672
    env_file:
      - ./.develop.env
    networks:
      - backend
      - mongodb_internal

  sensordata-service:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
      args:
        - BUILD_CONTEXT=sensordata-service
    hostname: sensordata-service
    volumes: 
      - ./backend/sensordata-service:/base/backend/sensordata-service/
      - ./backend/proto:/base/backend/proto/
      - ./backend/service-types/:/base/backend/service-types/
      - /base/node_modules
    # depends_on:
    #   - rabbitmq
    # environment:
    #   WAIT_HOSTS: rabbitmq:5672
    #   WAIT_TIMEOUT: 120
    #   WAIT_SLEEP_INTERVAL: 5
    env_file:
      - ./.develop.env
    networks:
      - backend
  
  # webclient:
  #   build: ./frontend
  #   volumes:
  #       - ./frontend:/var/www/frontend
  #       - /var/www/frontend/node_modules
  #   ports:
  #       - 4200:4200
  #   networks:
  #     - frontend

volumes:
  mongodb_data_container:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
  mongodb_internal:
    driver: bridge